### **Description**

The data used in the study was collected from a randomly selected sample of mobile phone users in the six Class 1 metropolises of India— Bengaluru, Chennai, Delhi, Kolkata, Mumbai and Hyderabad. These cities had seen a high number of active cases (22.30% of all cases), and deaths due to COVID-19 (37.99% of all cases), and the shortage of medical facilities. Respondents were residents of the city, aged between 21 and 60 years—randomly selected from a list of mobile telephone users. The survey was undertaken during the months of August and September 2020 (when the lockdown had ended, but COVID cases and deaths were rising rapidly) and then resurveyed again in July-August 2021 (after the second wave had ended). These periods are referred to as T1 and T2, respectively.

The survey was administered using the abridged shorter version of the DASS questionnaire, DASS-21 (Lovibond & Lovibond, 1995). The raw scores were used to create z-scores, which were then recoded into five categories (normal, mild, moderate, severe and extremely severe) following the methodology suggested by Lovibond and Lovibond (1995).

####**DASS-21 (Depression Anxiety Stress Scale – 21 items)** is a widely used psychological assessment tool developed by Peter Lovibond and Sue Lovibond. It is a shortened version of the original 42-item DASS and is designed to measure three related negative emotional states: Depression, Anxiety, and Stress.

The scale consists of 21 self-report items, with 7 items allocated to each subscale. Respondents rate how much each statement applied to them over the past week using a 4-point Likert scale ranging from 0 (“Did not apply to me at all”) to 3 (“Applied to me very much or most of the time”).

Scores for each subscale are calculated by summing the relevant items (and often multiplying by two to maintain comparability with the original DASS-42). Higher scores indicate greater levels of psychological distress. The DASS-21 is widely used in research and clinical settings due to its reliability, validity, and ability to distinguish between symptoms of depression, anxiety, and stress.

###**Motive behind analysis**

As I proceed further I will go through various steps and analyse the data end-to-end to figure out the possible factors of causing mental health detereoriation and will try to gain other insights from it.

In [ ]:
import numpy as np
import pandas as pd
mh = pd.read_csv('/content/adult mental health in indian metro cities 2001-2021 (reformed).csv')


In [ ]:
# Install itables
%pip install itables

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 23.6 MB/s eta 0:00:00


In [ ]:
from itables import init_notebook_mode
init_notebook_mode(all_interactive=True)
mh.head()

Loading ITables v2.7.0 from the internet... (need help?)


###**Column Descriptions:**

T1 → 1st phase, Aug–Sept 2020 (post-lockdown, rising cases)

T2 → 2nd phase, July–Aug 2021 (post second wave)
####**Identification & Demographics**

* slno – Serial number (unique respondent ID)

* name – Respondent name (if anonymized, coded ID)

* city – Metro city of residence (Bengaluru, Chennai, Delhi, Kolkata, Mumbai, Hyderabad)

* age – Age (21–60 years)

* sex – Gender of respondent

* religion – Religious affiliation

* caste – Social category

* study_level – Highest education level completed

* occupation – Type of occupation

* empl_st_before_lckdwn – Employment status before lockdown

* pymnt_st_main_erng_memb – Payment/salary status of main earning member

####**Household Characteristics**

* family_mems – Total family members

* agd_memb_above60 – Family members aged above 60

* mrd_and_spouse_living_together_or_not – Marital cohabitation status

* residential_pattern – Type of housing arrangement

* owned/rented – Housing ownership status

* change_of_occ – Change in respondent’s occupation

* change_of_occ_mainmember – Change in occupation of main earning member

* married_unmarried – Marital status

* residence_change – Whether residence changed during pandemic

* leisure_time T1/T2 – Change in leisure time

#### **Economic Condition (T1 & T2)**

* family_economicaly_affected T1/T2 – Whether family income was affected

* monthly_expenditure T1/T2 – Total monthly household expenditure

* mpce T1/T2 – Monthly Per Capita Expenditure

* fmpce T1/T2 – Family Monthly Total Expenditure (for more refer below)

* education_of_children T1/T2 – Impact on children’s education

####**COVID & Health Status (T1 & T2)**

* covid_case T1/T2 – Whether respondent had COVID

* fam_mem_suff_hyp-tens/bp/dbts/canc T1/T2 – Family member with chronic illness (hypertension, BP, diabetes, cancer)

####**DASS-21 Symptom Items (T1 & T2)**

Each of these represents one DASS-21 question (0–3 scale):

Examples:

* finding_hard_to_wind_down – Difficulty relaxing

* dry_mouth – Experience of dry mouth

* not_experiencing_+ve_felling – Lack of positive feelings

* breathing_difficulty – Shortness of breath

* difficulty_in_initiative_to_do_things – Low motivation

* felt_downhearted_and_blue – Sadness/depressive mood

* felt_life_is_meaningless – Feeling life lacks meaning

etc.

(All are repeated for T1 and T2.)

####**Mental Health Scores**

* depression T1/T2 – Depression subscale score

* depression_level T1/T2 – Severity category (Normal–Extremely Severe)

* relative_dep – Change in depression between T1 and T2

* anxiety T1/T2 – Anxiety subscale score

* anxiety_level T1/T2 – Anxiety severity category

* relative_anx – Change in anxiety

* stress T1/T2 – Stress subscale score

* stress_level T1/T2 – Stress severity category

* relative_stress – Change in stress

* dass21_raw T1 – Total raw DASS-21 score

* zdass21 T1 – Standardized (z-score) DASS-21 score

####  **Monthly Per Capita Expenditure(MPCE)** → It’s commonly used in Indian surveys like National Sample Survey Office (NSSO).

> MPCE = (Total household monthly consumption expenditure) / (number of household members)

**fmpce:**
#####   fmpce -> the rounded up monthly income figures or Family MPCE are converted into USD which was given the colun name -> fmpce.
The corresponding 1st column -> fmpce T1 represents the gross family income in T1 phase and 2nd column -> fmpce T2 represnts the gross family income in T2 phase.

In [ ]:
mh.head(2)

,slno,name,city,age,sex,religion,caste,study_level,occupation,empl_st_before_lckdwn,...,anxiety T2,anxiety_level T2,relative_anx,stress T1,stress_level T1,stress T2,stress_level T2,relative_stress,dass21_raw T1,zdass21 T1
0,5056,SOUMYA DASGUPTA,Kolkata,46,Male,Hindu,General,Graduation,ADVOCATE,Self-employed,...,18,Severe,Deterioration,8,Normal,20,Moderate,Deterioration,10.000000,-0.117815
1,5058,TITAS ROY,Kolkata,28,Male,Hindu,General,Above graduation,RESEARCH ANALYS,Full-time salaried,...,0,Normal,Same,10,Normal,6,Normal,Same,5.333334,-0.577837


#####
 As I didn't understand what 'zdass21' was, I performed these following tests.

In [ ]:
np.corrcoef(mh['dass21_raw'], mh['zdass21'])

array([[1.        , 0.99999119],
       [0.99999119, 1.        ]])

#####
* As I analysed the correlation value I found it is near 1 but min(zdass21) and max(zdass21) not lying between [-1,1]. So this row is not correaltional coefficient.

In [ ]:
mh['zdass21'].mean()

np.float64(0.031169276149899398)

In [ ]:
mh['zdass21'].std()

0.9763592548840906

#####
* So mean ~ 0 and std ~ 1, this says that column 'zdass21' is  a normalised column of 'dass21_raw'.

In [ ]:
mh.head(2)

,city,name,age,sex,religion,caste,study_level,study_level(specific),occupation,empl_st_before_lckdwn,...,anxiety T2,anxiety_level T2,relative_anx,stress T1,stress_level T1,stress T2,stress_level T2,relative_stress,dass21_raw T1,zdass21 T1
0,Kolkata,SOUMYA DASGUPTA,46,Male,Hindu,General,Graduation,LLB,ADVOCATE,Self-employed,...,18,Severe,Deterioration,8,Normal,20,Moderate,Deterioration,10.000000,-0.117815
1,Kolkata,TITAS ROY,28,Male,Hindu,General,Above graduation,MASTERS,RESEARCH ANALYS,Full-time salaried,...,0,Normal,Same,10,Normal,6,Normal,Same,5.333334,-0.577837


####**Problems with the dataset:**

* In the expenditure columns (monthly_expenditure, fmpce, mpce) there is someone whose all entries are 0. `accuracy`    *dealt*

* There are entries which has (monthly_expenditure, fmpce, mpce)T1 == 0 but T2 != 0 and vice-versa `accuracy`     *dealt*

* There are missing values in 'monthly_expenditure T1/T2', 'fmpce T1/T2', 'mpce T1/T2', 'education_of_children T1/T2'  `completeness` *somewhat handled*

* In the 'occupation' column there are entries in uppercase `consistency` *dealt*

* In the 'name' column there are entries in lowercase `consistency`

* We will work with INR, so we need to make the 'mpce' column into INR currency from USD `accuracy` *dealt*

* There's no dass21 section for T2 phase `feature engineering`

In [ ]:
mh.describe(include='all')


Loading ITables v2.7.0 from the internet... (need help?)


In [ ]:
mh[mh['name'] == 'Srinivas']

Loading ITables v2.7.0 from the internet... (need help?)


In [ ]:
mh.sample(10)

Loading ITables v2.7.0 from the internet... (need help?)


In [ ]:
#Check duplicates
mh['slno'].duplicated().sum()


np.int64(0)

#### **Missing value dealing in column: `monthly_expenditure T1`**

In [ ]:
mh[mh['monthly_expenditure T1'].isna()]

Loading ITables v2.7.0 from the internet... (need help?)


* row[465] has no information in economic condition in T1 but T2.
* row[73] has no information in economic condition in T1 but in T2 they are filled with 0's.

 As theres no way of retrieving these missing informations, I'm removing these particular columns and else they would cause disruptions in our future analysis.

In [ ]:
mh1 = mh.copy()
mh1.drop([73,465], inplace=True)
mh1[mh1['monthly_expenditure T1'].isna()]
mh = mh1.copy()

In [ ]:
mh[mh['monthly_expenditure T1'].isna()]

Loading ITables v2.7.0 from the internet... (need help?)


#### **Missing value dealing in column: `monthly_expenditure T2`**

In [ ]:
mh[mh['monthly_expenditure T2'].isna()]

Loading ITables v2.7.0 from the internet... (need help?)


* row[86] has no information in economic condition in T1 but T2.
* row[529] has no information in economic condition in T1 but in T2 they are filled with 0's.

 As theres no way of retrieving these missing informations, I'm removing these particular columns and else they would cause disruptions in our future analysis.

In [ ]:
mh2 = mh.copy()
mh2.drop([86,529], inplace=True)
mh2[mh2['monthly_expenditure T2'].isna()]
mh = mh2.copy()


In [ ]:
mh[mh['monthly_expenditure T1'].isna()]

Loading ITables v2.7.0 from the internet... (need help?)


In [ ]:
mh[mh['monthly_expenditure T2'].isna()]

Loading ITables v2.7.0 from the internet... (need help?)


####
* **Missing and inconsistent values removed from columns `monthly_expenditure T1` and `monthly_expenditure T2`**

In [ ]:
mh[mh['fmpce T1'].isna()]
mh[mh['fmpce T2'].isna()]
mh[mh['mpce T1'].isna()]
mh[mh['mpce T2'].isna()]

Loading ITables v2.7.0 from the internet... (need help?)


####
* **We dealt with the Missing inconsistent values of `fmpce T1/T2` and `mpce T1/T2` through previous operations**

In [ ]:
mh.describe(include='all')

Loading ITables v2.7.0 from the internet... (need help?)


####
 **There are still missing values in `education_of_children T1
/T2`**
* For the moment we will keep those and treat the missing entries as NaN

**Possible Solution:**

As economic status is directly related to education of child, so if we observe that a certain family's economic condition from phase T1 to T2,
* got better, we could assign `not affected` in T2
* if it got worse and the change is small and the family is in economically well enough, we could assign `not affected` in T2
* if it got worse and the change cannot be considered as small although not a drastic change either we could assign `somewhat affected` in T2
* if it got worse and the change is drastic, we could assign `severely affected` in T2

If economic status of a certain family in phase T1 is,
* better, we could assign `not affected`
* somewhat better, we could assign `somewhat affected`
* not well enogh, we could assign `severely affected`

In [ ]:
# Missing values in 'education_of_children T1'

mh['education_of_children T1'].isna().sum()

np.int64(201)

In [ ]:
# Missing values in 'education_of_children T2'

mh['education_of_children T2'].isna().sum()

np.int64(146)

In [ ]:
# Missing values in both 'education_of_children T1/t2'

no_children_edu = mh[(mh['education_of_children T1'].isna()) & (mh['education_of_children T2'].isna())]

# Could be possible that they have no child or child death due to covid or they genuinely did not provided information

Loading ITables v2.7.0 from the internet... (need help?)


###**Missing values in `monthly_expenditure T2`:**

In [ ]:
b = (mh['monthly_expenditure T1'] <= mh['monthly_expenditure T2']) & ((mh['education_of_children T1'].notna())) & (mh['education_of_children T2'].isna()) & (mh['mrd_and_spouse_living_together_or_not']!='Unmarried')
mh[b]

Loading ITables v2.7.0 from the internet... (need help?)


#####
Respondents whose `monthly_expenditure T2` was greater than or equal to T1 and who were married, but had missing values in `education_of_children T2` despite having valid responses in `education_of_children T1`, were assigned the category `somewhat affecte` for `education_of_children T2`.
* This imputation was performed using a mode-based approach, as`somewhat affecte` was the most frequently occurring category in the dataset. Given the relative stability or increase in household expenditure across phases, this category was considered the most statistically and contextually appropriate representation for the missing responses.

In [ ]:
mh.loc[b, 'education_of_children T2'] = mh.loc[b, 'education_of_children T2'].fillna('Somewhat affected')
mh[b]

Loading ITables v2.7.0 from the internet... (need help?)


In [ ]:
mh['education_of_children T2'].describe()

Loading ITables v2.7.0 from the internet... (need help?)


#####
* Non-Null value count in mh['education_of_children T2'] went to **852**



###**Missing values in `monthly_expenditure T1`:**

In [ ]:
a = ((mh['education_of_children T1'].isna()) & (mh['education_of_children T2'].notna()) & (mh['mrd_and_spouse_living_together_or_not']!='Unmarried'))
a1 = (a & (abs(mh['monthly_expenditure T1'] - mh['monthly_expenditure T2'])<= 2000))
mh[a1]

Loading ITables v2.7.0 from the internet... (need help?)


####
For respondents (married) with missing values in `education_of_children T1` but available values in `education_of_children T2`, the T1 values were imputed using the corresponding T2 values when the difference in monthly_expenditure between T1 and T2 was less than ₹2000
* This approach is based on the assumption that households whose monthly expenditure did not change substantially across the two phases, were likely to  remain in a almost similar economic status over a span of one year, and therefore were expected to maintain similar educational expenditure patterns for children.


In [ ]:
mh.loc[a1, 'education_of_children T1'] = mh.loc[a1, 'education_of_children T2']
mh[a1]


Loading ITables v2.7.0 from the internet... (need help?)


In [ ]:
mh['education_of_children T1'].describe()

Loading ITables v2.7.0 from the internet... (need help?)


#####
* Non-Null value count in mh['education_of_children T1'] went to **806**

In [ ]:
a = ((mh['education_of_children T1'].isna()) & (mh['education_of_children T2'].notna()) & (mh['mrd_and_spouse_living_together_or_not']!='Unmarried'))
a2 = (a & ((mh['monthly_expenditure T1'] - mh['monthly_expenditure T2']) >= 0) & ((mh['education_of_children T2']=='Not affected') | (mh['education_of_children T2']=='Somewhat affected')))
mh[a2]


Loading ITables v2.7.0 from the internet... (need help?)


####
For married respondents with missing values in `education_of_children T1` but available responses in `education_of_children T2`, the T1 values were imputed using the corresponding T2 values when monthly expenditure decreased from T1 to T2 and `education_of_children T2` was reported as `Somewhat affecte` or `Not affected`.
* This approach is based on the assumption that even if households experienced a decline in economic status over time, families that reported only moderate or no impact on children’s education in T2 were likely to have maintained similar educational expenditure patterns in the earlier phase T1.

In [ ]:
mh.loc[a2, 'education_of_children T1'] = mh.loc[a2, 'education_of_children T2']
mh[a2]

Loading ITables v2.7.0 from the internet... (need help?)


In [ ]:
mh['education_of_children T1'].describe()

Loading ITables v2.7.0 from the internet... (need help?)


#####
* Non-Null value count in mh['education_of_children T1'] went to **828**

In [ ]:
mh['education_of_children T1'].isna().sum()

np.int64(162)

In [ ]:
mh['education_of_children T2'].isna().sum()

np.int64(138)

In [ ]:
c = ((mh['education_of_children T1'].notna()) & (mh['education_of_children T2'].isna()) & (mh['mrd_and_spouse_living_together_or_not']!='Unmarried'))
c1 = (c & ((mh['monthly_expenditure T1'] - mh['monthly_expenditure T2']) >= 5000) & ((mh['education_of_children T1']=='Severely affected') | (mh['education_of_children T1']=='Somewhat affected')))
mh[c1]

Loading ITables v2.7.0 from the internet... (need help?)


####**Missing values in `education_of_children T2`:**

#####
For married respondents, those who has missing responds in `education_of_children T2` but available response in `education_of_children T1`, the T2 values were imputed into corresponding T1 values when the families experienced a decline in `monthly expenditure` which is more than 5000, from T1 to T2.
* This approach is based on the assumption that the households whose children's education was already affected in T1 and faced a significant economic decline are likely to remain in the similar or worsening economic condition, thereby maintaining comparable educational impact status in T2.


In [ ]:
mh.loc[c1, 'education_of_children T2'] = mh.loc[c1, 'education_of_children T1']
mh[c1]

Loading ITables v2.7.0 from the internet... (need help?)


In [ ]:
mh['education_of_children T1'].isna().sum()

np.int64(162)

In [ ]:
mh['education_of_children T2'].isna().sum()

np.int64(129)

#### **Remaining Nan values in `education_of_children T1/T2`**
* The remaining NaN values cannot be filled with statistical approach, so we keep them as they are.
* Respondents whose both sections are blank, we are not dealing with them as there could be a possibility that they have no childrens, or they genuinely did not want to provide informations.

##### **There are entries which has (monthly_expenditure, fmpce, mpce)T1 == 0 but T2 != 0**

#####
* As these cases could potentially introduce inconsistencies into the analysis, and given that their frequency was relatively low compared to the overall dataset size, they were removed from the dataset.

In [ ]:
d1 = mh[mh['monthly_expenditure T1']==0]
mh.drop(d1.index , inplace=True)
d1




Loading ITables v2.7.0 from the internet... (need help?)


##### **There are entries which has (monthly_expenditure, fmpce, mpce)T2 == 0 but T1 != 0**

#####
* As these cases could potentially introduce inconsistencies into the analysis, and given that their frequency was relatively low compared to the overall dataset size, they were removed from the dataset.

In [ ]:
d2 = mh[mh['monthly_expenditure T2']==0]
mh.drop(d2.index , inplace=True)
d2

Loading ITables v2.7.0 from the internet... (need help?)


#####**In the 'occupation' column there are entries in uppercase consistency**

In [ ]:
mh['occupation'] = mh['occupation'].str.lower()
mh.head()

Loading ITables v2.7.0 from the internet... (need help?)


In [ ]:
aa = (mh['monthly_expenditure T1']/mh['fmpce T1'])
aa.describe()
# as theres no jump in percentiles, so input datas are correct.

Loading ITables v2.7.0 from the internet... (need help?)


In [ ]:
T1_usd_value = (mh['monthly_expenditure T1']/mh['fmpce T1']).mean()
T1_usd_value  # 1USD equivalent in T1 phase

np.float64(73.50419959936725)

In [ ]:
mh = pd.read_csv('/content/adult mental health in indian metro cities 2001-2021 (reformed).csv')

In [ ]:
mh

Loading ITables v2.7.0 from the internet... (need help?)


#####
**mpce: USD to INR**

In [ ]:
mh['mpce T1'] = np.round(mh['mpce T1']*T1_usd_value)
mh

Loading ITables v2.7.0 from the internet... (need help?)


In [ ]:
bb = (mh['monthly_expenditure T2']/mh['fmpce T2'])
bb.describe()
# as theres no jump in percentiles, so input datas are correct.

Loading ITables v2.7.0 from the internet... (need help?)


In [ ]:
T2_usd_value = (mh['monthly_expenditure T2']/mh['fmpce T2']).mean()
T2_usd_value  # 1USD equivalent in T2 phase

np.float64(78.40705987038487)

In [ ]:
mh['mpce T2'] = np.round(mh['mpce T2']*T2_usd_value)
mh

Loading ITables v2.7.0 from the internet... (need help?)




**Value of rupees decreased:**
##### I made the conclusion by looking into the same figures in family income columns of both phase but difference in corresponding fmpce values.
As both surveys are performed in two different phases, and (fmpce T1) > (fmpce T2), which represnts that due to inflation and global economy, value of rupees decreased. We are saving both columns for future purpose.

* For now we will be working with rupee columns. For that case we need to convert the the mpce column from usd to rupees. We will be using the MPCE formula and total member counts in both phases.

#####
As monthly expenditure = fmpce, we are removing them

In [ ]:
mh = mh.drop(columns=['fmpce T1', 'fmpce T2'])


KeyError: "['fmpce T1', 'fmpce T2'] not found in axis"

In [ ]:
mh

Loading ITables v2.7.0 from the internet... (need help?)


### **As of now we have dealt with almost all problems with our dataset, and it is ready for further analysis, which will be performed on a another notebook.**

In [ ]:
mh.to_csv('/content/adult mental health in indian metro cities 2001-2021 (reformed).csv', index=False)